### ISSUE TITLE
Confusion in = You need to download dlib model. Put it in assets as sp68.dat file. The file is heavy ~70 Mbytes.

### ISSUE THREAD

**Issue by ParthP-7** [oleg-sta/FaceMaskExample#1]
Confusion on this part. The link provided by you has multiple files. Which files are we supposed to download and out in asset

**Comment by oleg-sta** [comment]
Added description:
https://github.com/oleg-sta/FaceMaskExample/commit/291afc4053ee844d9fee7ce42dab1d3a84c8a216
