### ISSUE TITLE
It takes about a minute to load camera preview for the first time when you start the app.. Is there anyway by which we can speed up this process? May be opencv library is taking time to load

### ISSUE THREAD

**Issue by ParthP-7** [oleg-sta/FaceMaskExample#4]

**Comment by oleg-sta** [comment]
Added in the reamde: "Note. Loading model sp68.dat is very heavy task, it can take several seconds or dozen seconds to be uploaded. You could try to retrain model and decrease size and therefore size of the application and initialization time."
