### ISSUE TITLE
Error in maven link 

### ISSUE THREAD

**Issue by ntqp97** [oleg-sta/FaceMaskExample#5]
When building the project in android studio. it gave an error: "Could not GET 'https://dl.bintray.com/olegst/maven/com/stoleg/vrface/1.1.3/vrface-1.1.3.pom'. Received status code 403 from server: Forbidden"

Is the maven link off? @oleg-sta

**Comment by dhiogoboza** [comment]
It is the same for me.

**Comment by oleg-sta** [comment]
i need to migrate from bintray to jfrog: https://www.jfrog.com/confluence/display/BT/JFrog+Bintray+Migration+Guide, I'll check it later.

**Comment by oleg-sta** [comment]
Should be fixed here: https://github.com/oleg-sta/FaceMaskExample/commit/5d341fb035bcd854403f27a274f539e507b08d1c

**Comment by ntqp97** [comment]
> Should be fixed here: [5d341fb](https://github.com/oleg-sta/FaceMaskExample/commit/5d341fb035bcd854403f27a274f539e507b08d1c)


I can't find GITHUB_TOKEN anywhere. Please help me, thank you.

**Comment by oleg-sta** [comment]
Generate your own GITHUB_TOKEN: https://docs.github.com/en/github/authenticating-to-github/keeping-your-account-and-data-secure/creating-a-personal-access-token
